import { useMemo, useState } from "react";
import { IconAlertTriangle, IconCheck, IconChevronRight, IconClock, IconFileCheck, IconHistory, IconLock, IconShieldCheck, IconWallet } from "@tabler/icons-react";

const months = ["Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"];
const money = new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 0 });

export function ApprovalPage({ settings, rows, annualPool, year, connection, costOverrides = [], onSaveCostOverrides, onBack }) {
  const storageKey = `marlin-management-approvals-${year}`;
  const [approvals, setApprovals] = useState(()=>{ try{return JSON.parse(localStorage.getItem(storageKey)||"{}");}catch{return{};} });
  const [selectedMonth,setSelectedMonth]=useState(rows[0]?.month||1);
  const historical = year < 2026;
  const pendingCosts = costOverrides.filter((item)=>item.status==="pending" && new Date(item.documentDate).getFullYear()===year);
  const periods = useMemo(()=>months.map((monthName,index)=>{
    const month=index+1; const row=rows.find((item)=>item.month===month);
    return {month,monthName,row,hasData:Boolean(row),approved:Boolean(approvals[month]),risk:Boolean(row&&(row.uncoveredCostLines||row.unlinkedReturnLines))};
  }),[approvals,rows]);
  const selected=periods.find((item)=>item.month===selectedMonth)||periods[0];
  const approvedCount=periods.filter((item)=>item.approved).length;
  const pendingCount=periods.filter((item)=>item.hasData&&!item.approved).length;
  const riskCount=periods.filter((item)=>item.risk).length;
  const saveApprovals=(next)=>{setApprovals(next);localStorage.setItem(storageKey,JSON.stringify(next));};
  const approvePeriod=()=>{if(historical||!selected.hasData)return;saveApprovals({...approvals,[selected.month]:{approvedAt:new Date().toISOString(),approvedBy:"Yönetim",locked:settings.lockAfterApproval}});};
  const reopenPeriod=()=>{const next={...approvals};delete next[selected.month];saveApprovals(next);};
  const approveCost=(id)=>onSaveCostOverrides(costOverrides.map((item)=>item.id===id?{...item,status:"approved",approvedAt:new Date().toISOString(),approvedBy:"Yönetim"}:item));

  return <main className="page approval-page" id="top">
    <section className="page-heading approval-heading"><div><p className="eyebrow">Yönetim kararı</p><h1>Onay ve Kapanış</h1><p>{historical?`${year} verileri yalnız karşılaştırma amaçlıdır; bu sistemle havuz dağıtımı yapılmadı.`:"2026 havuz dönemlerini ve manuel maliyet kararlarını tek aşamada onaylayın."}</p></div><span className={connection.connected?"connection-live":"connection-demo"}>{connection.connected?"CPM bağlı · salt okunur":"Pilot veri"}</span></section>
    <section className="approval-kpis"><article><span><IconLock/></span><div><small>Yönetim onaylı dönem</small><strong>{historical?"—":approvedCount}</strong><p>{historical?"Tarihsel kayıt":"Nihai karar tamamlandı"}</p></div></article><article><span className="approval-kpi--blue"><IconFileCheck/></span><div><small>Onay bekleyen dönem</small><strong>{historical?"—":pendingCount}</strong><p>Verisi oluşan dönemler</p></div></article><article><span className="approval-kpi--amber"><IconAlertTriangle/></span><div><small>Görünür veri riski</small><strong>{riskCount}</strong><p>Onayı kilitlemez, inceleme gerektirir</p></div></article><article className="approval-kpi__pool"><span><IconWallet/></span><div><small>Tahmini net havuz</small><strong>{historical?"Dağıtım yok":`${money.format(annualPool)} TL`}</strong><p>{year}</p></div></article></section>
    <div className="approval-layout"><section className="panel period-panel"><div className="panel-heading"><div><h2>Aylık Yönetim Onayı</h2><p>{historical?"Bu sistem öncesi tarihsel görünüm":"Veri bekliyor → Yönetim onayı bekliyor → Onaylandı"}</p></div></div><div className="period-table-wrap"><table className="period-table"><thead><tr><th>Dönem</th><th>Veri güveni</th><th>Dağıtıma esas kâr</th><th>Havuz katkısı</th><th>Yönetim durumu</th></tr></thead><tbody>{periods.map((period)=><tr key={period.month} className={selected.month===period.month?"selected-period":""} onClick={()=>setSelectedMonth(period.month)}><th>{period.monthName}<small>{period.hasData?`${money.format(period.row.sales)} TL satış`:"Veri bekleniyor"}</small></th><td>{period.hasData?(period.risk?<span className="negative">İnceleme var</span>:<span className="positive">Doğrulandı</span>):"—"}</td><td>{period.hasData?`${money.format(period.row.profit)} TL`:"—"}</td><td className="positive">{period.hasData?`${money.format(period.row.contribution)} TL`:"—"}</td><td>{historical?<span className="goal-status">Bu sistemde dağıtılmadı</span>:period.approved?<span className="goal-status goal-status--approved">Onaylandı</span>:period.hasData?<span className="goal-status goal-status--pending">Yönetim onayı bekliyor</span>:<span className="goal-status">Veri bekliyor</span>}</td></tr>)}</tbody></table></div></section>
    <aside className="approval-detail"><div className="approval-detail__title"><div><p className="eyebrow">Seçili dönem</p><h2>{selected.monthName} {year}</h2></div>{selected.approved&&<IconCheck/>}</div>{historical?<div className="approval-empty"><IconHistory/><div><strong>Tarihsel veri</strong><p>Bu yılda mevcut sistemle havuz dağıtımı ve yönetim onayı yapılmadı.</p></div></div>:!selected.hasData?<div className="approval-empty"><IconClock/><div><strong>Veri bekleniyor</strong><p>CPM dönem verisi oluştuğunda yönetim onayı açılır.</p></div></div>:<><dl className="approval-values"><div><dt>Dağıtıma esas kâr</dt><dd>{money.format(selected.row.profit)} TL</dd></div><div><dt>Havuz katkısı</dt><dd className="positive">{money.format(selected.row.contribution)} TL</dd></div><div><dt>Maliyet kapsamı</dt><dd>%{Number(selected.row.costCoveragePct||0).toFixed(1).replace(".",",")}</dd></div></dl>{selected.risk&&<div className="approval-blocker"><IconAlertTriangle/><div><strong>İnceleme notu</strong><p>Eksik maliyet veya bağlantısız iade bulunuyor. Bu durum görünürdür fakat yönetim kararını teknik olarak engellemez.</p></div></div>}<div className="approval-actions">{selected.approved?<button className="secondary-button" onClick={reopenPeriod}>Onayı geri aç</button>:<button className="primary-action" onClick={approvePeriod}><IconShieldCheck size={17}/> Yönetim onayı ver</button>}</div></>}
    {pendingCosts.length>0&&<div className="approval-history"><div className="approval-history__head"><IconHistory/><strong>Manuel maliyet onayları</strong></div>{pendingCosts.map((item)=><div key={item.id}><span className="history-icon back"><IconAlertTriangle/></span><p><strong>{item.cardCode} · {item.documentNo}</strong><small>{money.format(item.unitCost)} TL birim · {item.reason}</small></p><button className="row-action" onClick={()=>approveCost(item.id)} aria-label="Maliyeti onayla"><IconCheck/></button></div>)}</div>}<button className="back-to-ledger" onClick={onBack}>Havuza dön <IconChevronRight size={16}/></button></aside></div>
  </main>;
}
