import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { IconBuilding, IconChartBar, IconDatabase, IconDiscount, IconReportAnalytics, IconSearch, IconUsers, IconWallet } from "@tabler/icons-react";
import { calculateEmployeeDistribution } from "./distribution";

const money=new Intl.NumberFormat("tr-TR",{maximumFractionDigits:0});
const tabs=[
  ["summary","Yönetim Özeti"],["brand","Marka"],["dealer","Bayi"],["channel","Kanal / Modül"],["service","Teknik Servis"],["cost","Alım ve Maliyet"],["discount","İskonto ve İade"],["confidence","Veri Güveni"],["pool","Havuz Dağılımı"],
];
const pilotMethodRates={configuredLabor:"labor",configuredSrf:"srf",configuredTsr:"tsr",configuredRoad:"road"};

function aggregate(rows,keyFn,valueFn){const map=new Map();rows.forEach((row)=>{const key=keyFn(row)||"Tanımsız";const current=map.get(key)||{name:key,netSales:0,cost:0,profit:0,discount:0,returns:0,lines:0};const value=valueFn(row);Object.keys(value).forEach((key)=>current[key]=(current[key]||0)+Number(value[key]||0));current.lines+=1;map.set(key,current);});return [...map.values()].sort((a,b)=>b.netSales-a.netSales);}

export function ReportsPage({settings,employees,annualPool,year,rows}){
  const [active,setActive]=useState("summary");
  const [ledger,setLedger]=useState([]);
  const [query,setQuery]=useState("");
  const [loading,setLoading]=useState(true);
  useEffect(()=>{let cancelled=false;setLoading(true);fetch(`/api/audit-ledger?year=${year}&export=1`).then((response)=>response.json()).then((data)=>{if(!cancelled){setLedger(data.rows||[]);setLoading(false);}}).catch(()=>{if(!cancelled){setLedger([]);setLoading(false);}});return()=>{cancelled=true;};},[year]);
  const valued=useMemo(()=>ledger.map((row)=>{const sign=row.isSale?1:-1;const net=sign*Number(row.netAmount||0);const rateKey=pilotMethodRates[row.costMethod];const cost=row.lineCost!=null?Number(row.lineCost):rateKey?sign*Number(row.netAmount||0)*Number(settings.pilotCardCostRates?.[rateKey]??100)/100:0;return{...row,net,cost,profit:row.costMethod==="excludedIncome"?0:net-cost,discount:sign*Number(row.discountAmount||0),returns:row.isSale?0:Number(row.netAmount||0)};}),[ledger,settings.pilotCardCostRates]);
  const totals=valued.reduce((a,r)=>({netSales:a.netSales+r.net,cost:a.cost+r.cost,profit:a.profit+r.profit,discount:a.discount+r.discount,returns:a.returns+r.returns}),{netSales:0,cost:0,profit:0,discount:0,returns:0});
  const brand=aggregate(valued,r=>r.brand||"Tanımsız",r=>({netSales:r.net,cost:r.cost,profit:r.profit,discount:r.discount,returns:r.returns}));
  const dealer=aggregate(valued.filter(r=>String(r.customerCode||"").startsWith("DBS")),r=>r.customerCode,r=>({netSales:r.net,cost:r.cost,profit:r.profit,discount:r.discount,returns:r.returns}));
  const channel=aggregate(valued,r=>r.sourceDocumentType===64?"Teknik Servis":r.documentType===91?"Perakende Satış":r.documentType===85?"İrsaliyesiz Fatura":r.revenueSource==="provisional"?"Kapanmış / aktarılmış":"Satış Faturası",r=>({netSales:r.net,cost:r.cost,profit:r.profit,discount:r.discount,returns:r.returns}));
  const service=aggregate(valued.filter(r=>r.sourceDocumentType===64),r=>r.brand||"Tanımsız",r=>({netSales:r.net,cost:r.cost,profit:r.profit,discount:r.discount,returns:r.returns}));
  const costs=aggregate(valued,r=>({bulkPurchase:"Toplu alım stoku",priorPurchase:"Önceki son alım",nextPurchase:"Sonradan girilen alım",configuredLabor:"İşçilik oranı",configuredSrf:"SRF / BARNACLE",configuredTsr:"TSR oranı",configuredRoad:"YOL oranı",missingPurchase:"İnceleme gerekli",excludedIncome:"Kapsam dışı"}[r.costMethod]||r.costMethod),r=>({netSales:r.net,cost:r.cost,profit:r.profit}));
  const confidence=aggregate(valued,r=>({verified:"Faturayla doğrulandı",configured:"Oranla hesaplandı",review:"İnceleme gerekli",excluded:"Kapsam dışı"}[r.verificationStatus]||r.verificationStatus),r=>({netSales:r.net,cost:r.cost,profit:r.profit}));
  const distribution=useMemo(()=>calculateEmployeeDistribution(employees,settings,annualPool),[annualPool,employees,settings]);
  const pool=aggregate(distribution,r=>r.department,r=>({netSales:r.projectedShare,profit:r.projectedShare}));
  const datasets={brand,dealer,channel,service,cost:costs,confidence,pool};
  const current=datasets[active]||[];
  const filtered=current.filter((item)=>item.name.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR")));

  return <main className="page reports-page" id="top"><section className="page-heading reports-heading"><div><p className="eyebrow">CPM iş analitiği</p><h1>Raporlar Merkezi</h1><p>Satış, kârlılık, marka, bayi, kanal, servis, maliyet ve havuz sonuçlarını tek merkezde inceleyin.</p></div><span className="source-badge source-badge--live">{loading?"CPM okunuyor…":"CPM canlı · salt okunur"}</span></section>
  <section className="report-kpis"><article><span><IconChartBar/></span><div><small>Net satış</small><strong>{money.format(totals.netSales)} TL</strong><p>{money.format(ledger.length)} belge satırı</p></div></article><article><span className="report-kpi--green"><IconWallet/></span><div><small>Hesaplanan kâr</small><strong>{money.format(totals.profit)} TL</strong><p>Marj %{totals.netSales?(totals.profit/totals.netSales*100).toFixed(1):0}</p></div></article><article><span className="report-kpi--blue"><IconBuilding/></span><div><small>Bayi satışı</small><strong>{money.format(dealer.reduce((s,r)=>s+r.netSales,0))} TL</strong><p>DBS kodlu {dealer.length} bayi</p></div></article><article><span className="report-kpi--amber"><IconDatabase/></span><div><small>Teknik servis</small><strong>{money.format(service.reduce((s,r)=>s+r.netSales,0))} TL</strong><p>Kaynak evrak 64</p></div></article></section>
  <section className="panel"><div className="report-tabs">{tabs.map(([id,label])=><button key={id} className={active===id?"active":""} onClick={()=>setActive(id)}>{label}</button>)}</div></section>
  {active==="summary"?<div className="report-grid"><section className="panel department-report"><div className="panel-heading"><div><h2>En Yüksek Net Satışlı Markalar</h2><p>CPM stok kartı marka alanı</p></div></div><ResponsiveContainer width="100%" height={320}><BarChart data={brand.slice(0,10)}><CartesianGrid vertical={false} stroke="#e5e9ef"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tickFormatter={(v)=>`${Math.round(v/1e6)} Mn`}/><Tooltip formatter={(v)=>`${money.format(v)} TL`}/><Bar dataKey="netSales" fill="#0a3972" radius={[3,3,0,0]}/><Bar dataKey="profit" fill="#16884e" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></section><aside className="report-notes"><div className="report-notes__head"><IconReportAnalytics/><strong>Yönetim Özeti</strong></div><ul><li>{brand.length} marka satış hareketi oluşturdu.</li><li>DBS kodlu bayiler {money.format(dealer.reduce((s,r)=>s+r.netSales,0))} TL net satış yarattı.</li><li>Teknik servis kaynaklı satış {money.format(service.reduce((s,r)=>s+r.netSales,0))} TL.</li><li>{confidence.find(r=>r.name==="İnceleme gerekli")?.lines||0} satır maliyet incelemesi bekliyor.</li></ul></aside></div>:active==="discount"?<section className="panel distribution-report"><div className="panel-heading"><div><h2>İskonto ve İade Özeti</h2><p>Brüt satıştan düşülen ticari hareketler</p></div></div><div className="report-kpis"><article><span><IconDiscount/></span><div><small>İskonto</small><strong>{money.format(totals.discount)} TL</strong></div></article><article><span><IconChartBar/></span><div><small>İade</small><strong>{money.format(totals.returns)} TL</strong></div></article></div></section>:<section className="panel distribution-report"><div className="distribution-report__head"><div><h2>{tabs.find(([id])=>id===active)?.[1]}</h2><p>{filtered.length} analiz satırı</p></div><label className="goal-search"><IconSearch size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Ara"/></label></div><div className="table-scroll"><table className="report-table"><thead><tr><th>Boyut</th><th>Satır</th><th>Net satış / pay</th><th>Maliyet</th><th>Kâr</th><th>Marj</th></tr></thead><tbody>{filtered.map((item)=><tr key={item.name}><th>{item.name}</th><td>{money.format(item.lines)}</td><td>{money.format(item.netSales)} TL</td><td>{money.format(item.cost)} TL</td><td className={item.profit>=0?"positive":"negative"}>{money.format(item.profit)} TL</td><td>%{item.netSales?(item.profit/item.netSales*100).toFixed(1):0}</td></tr>)}{!filtered.length&&<tr><td colSpan="6" className="empty-state">Veri bulunamadı.</td></tr>}</tbody></table></div></section>}
  </main>;
}
